### PR TITLE
Fix truncate tail

### LINKED ISSUE #31: Sealed segment without IndexStart
```
[INFO]  raft: initial configuration: index=7 servers="[{Suffrage:Voter ID:00000001-0001-0001-0001-000000000001 Address:192.168.121.27:4419} {Suffrage:Voter ID:00000003-0003-0003-0003-000000000003 Address:192.168.121.217:4419} {Suffrage:Voter ID:00000002-0002-0002-0002-000000000002 Address:192.168.121.112:4419}]"
[INFO]  raft: entering follower state: follower="Node at 00000001-0001-0001-0001-000000000001 [Follower]" leader-address= leader-id=
[WARN]  raft: heartbeat timeout reached, not part of a stable configuration or a non-voter or not allowed to candidate, not triggering a leader election
[DEBUG] raft: lost leadership because received a requestVote with a newer term
[WARN]  raft: rejecting vote request since our last index is greater: candidate=00000003-0003-0003-0003-000000000003 last-index=424 last-candidate-index=423
[WARN]  raft: clearing log suffix: from=424 to=424

# Process is restarted

[ERROR] raft: failed to get log: index=1 error="sealed segment has no index block"
panic: sealed segment has no index block
goroutine 1 [running]:
github.com/hashicorp/raft.NewRaft(0xc0003423c0, {0x32b3ec0?, 0xc000355f50}, {0x32b7b90?, 0xc000342460}, {0x32b5b48?, 0xc000342460}, {0x32b3470?, 0xc000355ec0}, {0x32bb698, ...})
[...]
```

In this trace, raft is clearing the last index from the WAL (424). It calls `(w *WAL) DeleteRange()` which calls `(w *WAL) truncateTailLocked()`.

`truncateTailLocked()` seals the segment but does not set the IndexStart, which is wrong from my understanding. So at the next start, the segment is sealed without any IndexStart set, which triggers the panic from `(r *Reader) findFrameOffset`.

### PR DESCRIPTION
**Pull request by banks**
Fixes #31.

The WAL layer assumes that the tail index will be sealed during a tail truncate and marks it as such in the meta store but doesn't actually have a mechanism currently to force the segment writer to append an index block.

This PR fixes that by adding such a mechanism.

## Integration Tests

Since this is another issue that escaped due to lack of integration testing between the component layers, I've added a basic initial integration suite that uses WAL with real Segment/Meta/FS in some basic scenarios.

Although basic, two of the scenarios failed without the fix to call `ForceSeal` in this PR in the same way as #31. There is also at least one scenario that would have failed my initial integration with Consul before I had the snapshot behaviour correct (another integration testing miss).

Perhaps in the future we can extend this to cover other scenarios or to use fault injection or fuzzing etc. But for now this is a solid improvement over no integration tests!

### CODE REVIEW

**Comment by banks** [comment]
> I think one integration test that we need to make at some point is retro compatibility with the on disk format. This could be achieved by saving a few test scenarios with each released version and trying to open/read them in tests in main.

This is a great call. We've not made any changes to disk format since I first released this yet but when we do we should certainly have an upgrade test. I think you are suggesting that it would be worth having that anyway just in case we _accidentally_ change something. Not a bad call. I guess it wouldn't be too hard to write out a test dir into `testdata` with a flag and then have a test that tries to open and read that.

File: wal_stubs_test.go [hunk 1]
```diff
@@ -302,6 +309,20 @@ func (ts *testStorage) assertValidMetaState(t *testing.T) {
...
+			// sealed status matches meta since that is not always true e.g. just
+			// after an append that caused segment to seal but before the rotate has
+			// updated metadata. The thing we need to ensure is that if metadata says
+			// it's sealed that the actual segment is actually sealed and has an index
+			// block.
+			if !seg.SealTime.IsZero() {
+				sealed, indexStart, err := ts.Sealed()
+				require.NoError(t, err)
+				require.True(t, sealed)
+				require.NotEqual(t, 0, int(indexStart))
```
Comment (banks) [inline wal_stubs_test.go:324]: Realised I should also assert that the `seg.IndexStart` matches the `indexStart`. It's a _bit_ of a tautology in the sense that segments read from disk would actually populate `indexStart` from metadata in the first place but in these tests it would actually verify something useful: that the segment we just sealed reported it's index offset consistently and that it was actually updated in the meta data. I'll add that before I merge.
